#define NTERM			1
#define TERM			2
#define	UNION_SYM		3
#define LEFT_SYM		4
#define RIGHT_SYM		5
#define ERROR_SYM		6
#define PREC_SYM		7
#define INIT_SYM		8
#define INCL_SYM		9
#define TERM_TYPE_SYM	10
#define NTERM_TYPE_SYM	11
#define SEP				12
#define ALT				13
#define NTERM_TYPE_DEF	14
